Added error handling and sudo python install in code.sh
eastgenomics/eggd_MetricsOutput_MultiQC_parser pull request #4
Opened 2024-07-31 15:26 UTC by fletchercr

Changes:

- addressed some error handling in python code
- removed sudo in code.sh at python pip install command (found including sudo and not including both work -- https://platform.dnanexus.com/panx/projects/Gkj0FZQ4jPY48xpKqK149Kz9/data/pretesting/no_sudo_code.sh)

To do: clarification about which whl packages are required, and which can be dependent on "assetDepends" like https://github.com/eastgenomics/eggd_tandem_hunter/blob/main/dxapp.json#L77

2024-07-31 15:26 UTC, pep8speaks commented
Hello @fletchercr! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/edit_MetricsOutput.py`](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py):

> [Line 40:80](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L40): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 50:80](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L50): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 62:9](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L62): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 62:80](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 114:80](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L114): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 133:5](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L133): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 163:5](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L163): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 164:80](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L164): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 184:80](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L184): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 185:5](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L185): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 186:80](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L186): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)

2024-08-01 10:18 UTC, nadia31415 requested changes
There's some PEP 8 issues highlighted that need addressing,
There are lines over the character limit 
This has also flagged the use of bare 'except' on certain lines of code.  It will catch any and all exceptions. The reason this is not recommended is cause you don't know which exception you are catching.
To explain this, https://stackoverflow.com/questions/54948548/what-is-wrong-with-using-a-bare-except . This also details how to fix this

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4#-:-O3C-_s5716F-E0u74Ar:b197zal)* status: all files reviewed, 3 unresolved discussions (waiting on @fletchercr)

___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 62 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4#-O3CJ1UU9Jc0XYhzimYg:-O3CJ1UU9Jc0XYhzimYh:bf1vb09) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L62)):*
> ```Python
>                             )
>                             all_data.append(metric_values)
>         ### what should I do with this df? does it go in try? does return df go in try
> ```

Your df is in the try block so it it fine where it is, this comment can be deleted
___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4#-O3CNJWcCjBAj3OZS7BC:-O3CNJWcCjBAj3OZS7BD:b-vtq5va) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L66)):*
> ```Python
>         return df
>     except FileNotFoundError:
>         raise FileNotFoundError
> ```

I think this except statement can be moved to where you read in the file and before you read each line in the file. Also, you could raise an exception for not reading a file in correctly - https://stackoverflow.com/questions/5627425/what-is-a-good-way-to-handle-exceptions-when-trying-to-read-a-file-in-python
___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 153 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4#-O3CLZ4Y2be1ucf6lXH5:-O3CLZ4Y2be1ucf6lXH6:b5pme5g) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L153)):*
> ```Python
>     """
>     # replace NA string with null value
>     full_df.replace("NA", np.nan, inplace=True)
> ```

It may be better to use pandas to replace NA string e.g. 



_Code snippet:_
```Python
full_df.replace("NA", pd.NA, inplace=True)
```


<!-- Sent from Reviewable.io -->

2024-08-01 15:24 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4)* status: all files reviewed, 5 unresolved discussions (waiting on @fletchercr)

___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4#-O3DWXJd5UUanaddOz9o:-O3DWXJd5UUanaddOz9p:b-dfcy7b) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L134)):*
> ```Python
>         return edited_df
>     except:
>         print("Error with editing column headers")
> ```

if neither Median insert size are present then this error will be raised, but it should always be there as you've done an IF statement check. Also can you test this with a DNA/RNA that failed the pipeline  to see if the median insert size is populated. Not sure whether when a sample fails the pipeline some metrics are calculated and others arent, the brackets maybe "( NA )"
___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4#-O3DXQ6ODdxCzVke9cXU:-O3DXQ6P0X_FFwsXnuAF:bm5bol9) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/e6b54b4ad70b93ad8977ac5f21b36d5f3ef5aace/resources/home/dnanexus/edit_MetricsOutput.py#L164)):*
> ```Python
>         ].astype(float)
>     except:
>         print("Error: Could not convert CONTAMINATION_SCORE and CONTAMINATION_P_VALUE to floats")
> ```

Does this work if it is a mix of DNA and RNA?


<!-- Sent from Reviewable.io -->

2024-08-15 15:45 UTC, nadia31415 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fletchercr)



<!-- Sent from Reviewable.io -->

2024-08-15 15:45 UTC, merged